version: '3.4'

services:
  api-service-1: &api-service
    image: api-service
    hostname: api-service-1
    build:
      context: ./Services/APIService
      dockerfile: Dockerfile
    environment:
      - RUNNING_IN_CONTAINER=true
    networks:
      - backend_network

  api-service-2:
    <<: *api-service
    hostname: api-service-2

  api-service-3:
    <<: *api-service
    hostname: api-service-3

  api-service-4:
    <<: *api-service
    hostname: api-service-4

  client-service:
    image: client-service
    hostname: client-service
    build:
      context: ./Services/ClientService
      dockerfile: Dockerfile
    environment:
      - RUNNING_IN_CONTAINER=true
    networks:
      - backend_network

networks:
  backend_network:
    external: true
